### ISSUE TITLE
Intrinsics & Extrinsics

### ISSUE THREAD

**Issue by VanLinLin** [shenqq377/instance_detection_challenge#1]
Hello, can I get the Intrinsics & Extrinsics of the camera?

**Comment by shenqq377** [comment]
Sorry, we don't have such exact parameters because we've captured object profile images through mobilephone camera. We aim to immitate that we observe an object by eyes in real world. I suggest you consider using colmap to calculate these parameters from multiple profile images. If you are interested in Object Instance Detection, please check https://insdet.github.io.

**Comment by shenqq377** [comment]
Please check our InsDet Challenge Workshop @ ACCV 2024. The GoogleDrive link to test data is available now.

**Comment by VanLinLin** [comment]
Hello, I checked the Google Drive link and it's exciting. Is it a close set task or is it an open set task? And what is the input of the model when I generate the testing result? For example, my model will use the scene image with several objects as input, or can I use the scene image with several objects and the query object image as input?

**Comment by shenqq377** [comment]
It doesn't matter. You should provide  a simple description (including data，method，and setting) through submission. Pretrained models and external  data are allowed, but we don't allow using scene images (both in dev and test phase) as training data. Our ultimate aim to release this dataset is to simulate the real world robotics application, as we mentioned  in our paper NeurIPS D&B 2023.I strongly  suggest you test your code  through  dev phase.
